/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ELCOT
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    String cid = null;
    public int flag = 0;
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        passwd = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        reenter = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WAKE UP IT'S FOOD O'CLOCK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 11, 374, 43));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("NAME");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 96, 236, 56));
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 96, 229, 56));

        passwd.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        passwd.setForeground(new java.awt.Color(255, 255, 255));
        passwd.setText("PASSWORD");
        getContentPane().add(passwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 188, 236, 68));
        getContentPane().add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 188, 229, 68));

        reenter.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        reenter.setForeground(new java.awt.Color(255, 255, 255));
        reenter.setText("Re-enter Password");
        getContentPane().add(reenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 236, 55));
        getContentPane().add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 290, 229, 55));

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton2.setText("REGISTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 356, 176, 53));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Already Have an Account ?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 427, 214, 32));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("SIGN IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 427, 124, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ELCOT\\Downloads\\6th Sem\\OOAD\\OOAD\\bg.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection con ;
        if(pass1.getText().equals(pass2.getText()))
        {
            
            try 
            {
                flag = 1;
                Class.forName("com.mysql.cj.jdbc.Driver");
                
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/frs","root","Parkavi@2003");
                Statement stmt=con.createStatement();
                
                ResultSet f = stmt.executeQuery("select count(*) as t from customers");
                String count = null;
                while(f.next())
                {
                       count = f.getString("t");
                }
        //System.out.println("hello");
                 int coun = Integer.parseInt(count) + 1;
                 String c = "C"+coun;
                 cid = c;
                 System.out.println(c);
                 String name = name1.getText();
                 System.out.println(name);
                 String passwd = pass1.getText();
                 System.out.println(passwd);
                 int x = stmt.executeUpdate("insert into customers values('"+c+"','"+name1.getText()+"','"+pass1.getText()+"');");
                 if(x>1)
                     System.out.println("ooh");
                 else
                     System.out.println("hoo");
            } 
            catch (ClassNotFoundException ex) 
            {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
             System.out.println("Rewrite th correct Password");
             new Home().setVisible(true);
             
        }
        String[] cid1={cid,"1"};
         FRSMenu.main(cid1);
         dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel name;
    private javax.swing.JTextField name1;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JLabel passwd;
    private javax.swing.JLabel reenter;
    // End of variables declaration//GEN-END:variables
}
